"use client";
import {useEffect,useMemo,useState} from "react";
import * as XLSX from "xlsx";
import Papa from "papaparse";
import {Upload,Database,Users,Activity,Target,FileSpreadsheet,CheckCircle2,AlertCircle,ArrowRight} from "lucide-react";

type Row=Record<string,unknown>;
type ImportRecord={id:string;name:string;count:number;importedAt:string};
export type Pitch={id:number;importId?:string;pitcher:string;batter:string;pitchCall:string;playResult:string;side:number|null;height:number|null;velo:number|null;exitVelo:number|null;angle:number|null;spin:number|null;spinAxis:number|null;pitchType:string;date:string};
const STORAGE_KEY="racers-trackman-pitches-v1";
const FILES_KEY="racers-trackman-imports-v1";
function readImports():ImportRecord[]{try{const raw:unknown=JSON.parse(localStorage.getItem(FILES_KEY)||"[]");if(!Array.isArray(raw))return [];return raw.map((x:unknown):ImportRecord=>{if(typeof x==="string")return{id:"legacy-"+x,name:x,count:0,importedAt:""};if(x&&typeof x==="object"){const v=x as Partial<ImportRecord>;return{id:String(v.id??"legacy-unknown"),name:String(v.name??"Unknown import"),count:Number(v.count??0),importedAt:String(v.importedAt??"")}}return{id:"legacy-unknown",name:"Unknown import",count:0,importedAt:""}})}catch{return []}}
const aliases={
 pitcher:["Pitcher","PitcherName"], batter:["Batter","BatterName","Hitter"],
 pitchCall:["PitchCall"], playResult:["PlayResult"], side:["PlateLocSide","PlateLocSide (ft)"],
 height:["PlateLocHeight","PlateLocHeight (ft)"], velo:["RelSpeed","PitchVel"], exitVelo:["ExitSpeed"],
 angle:["Angle","LaunchAngle"], spin:["SpinRate"], spinAxis:["SpinAxis"], pitchType:["TaggedPitchType","AutoPitchType","PitchType"],
 gameDate:["Date","GameDate","PitchDate"]
};
function get(r:Row,n:keyof typeof aliases){for(const k of aliases[n])if(r[k]!==undefined&&r[k]!==null&&r[k]!=="")return r[k];return null}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null}
function normalize(rows:Row[]):Pitch[]{return rows.map((r,i)=>({id:i,pitcher:String(get(r,"pitcher")??"Unknown"),batter:String(get(r,"batter")??"Unknown"),pitchCall:String(get(r,"pitchCall")??""),playResult:String(get(r,"playResult")??""),side:num(get(r,"side")),height:num(get(r,"height")),velo:num(get(r,"velo")),exitVelo:(num(get(r,"exitVelo"))||0)>0?num(get(r,"exitVelo")):null,angle:num(get(r,"angle")),spin:num(get(r,"spin")),spinAxis:num(get(r,"spinAxis")),pitchType:String(get(r,"pitchType")??"Unknown"),date:String(get(r,"gameDate")??"")}))}
function parse(file:File){return new Promise<Row[]>((resolve,reject)=>{if(file.name.toLowerCase().endsWith(".xlsx")||file.name.toLowerCase().endsWith(".xls")){const rd=new FileReader();rd.onload=e=>{try{const wb=XLSX.read(e.target?.result,{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];resolve(XLSX.utils.sheet_to_json<Row>(ws,{defval:null}))}catch(err){reject(err)}};rd.readAsArrayBuffer(file)}else Papa.parse<Row>(file,{header:true,skipEmptyLines:true,complete:r=>resolve(r.data),error:e=>reject(e)})})}
function avg(a:(number|null)[]){const x=a.filter((v):v is number=>v!==null);return x.length?x.reduce((s,v)=>s+v,0)/x.length:0}
export default function ImportPage(){const [rows,setRows]=useState<Pitch[]>([]);const [imports,setImports]=useState<ImportRecord[]>([]);const [file,setFile]=useState("");const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");const hitters=useMemo(()=>Array.from(new Set(rows.map(r=>r.batter).filter(x=>x!=="Unknown"))),[rows]);const pitchers=useMemo(()=>Array.from(new Set(rows.map(r=>r.pitcher).filter(x=>x!=="Unknown"))),[rows]);const velo=avg(rows.map(r=>r.velo));const ev=avg(rows.map(r=>r.exitVelo));const spin=avg(rows.map(r=>r.spin));

async function upload(f:File){setBusy(true);setMsg("");try{const raw=await parse(f);if(!raw.length)throw new Error("No rows found.");const n=normalize(raw);const existing:Pitch[]=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");const imports=readImports();if(imports.some(x=>x.name===f.name)){setMsg("This filename has already been imported in this browser. Rename the file if it is a new TrackMan session.");setRows(existing);setFile(f.name);return}const importId=crypto.randomUUID();const combined=n.map((r,i)=>({...r,id:existing.length+i,importId}));const all=[...existing,...combined];const record={id:importId,name:f.name,count:n.length,importedAt:new Date().toISOString()};const nextImports=[...imports,record];localStorage.setItem(STORAGE_KEY,JSON.stringify(all));localStorage.setItem(FILES_KEY,JSON.stringify(nextImports));setImports(nextImports);setRows(combined);setFile(f.name);setMsg(`Imported ${n.length.toLocaleString()} pitches and added them to your running season total.`)}catch(e){setMsg(e instanceof Error?e.message:"Unable to import file.")}finally{setBusy(false)}}

function deleteImport(id:string){const record=imports.find(x=>x.id===id);if(!record)return;if(id.startsWith("legacy-")){const ok=window.confirm("These older uploads were saved before per-import tracking existed, so their pitches cannot be separated safely. Clear ALL legacy uploads now so you can re-upload them with individual deletion enabled?");if(!ok)return;const existing:Pitch[]=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");const remaining=existing.filter(p=>!!p.importId);const next=imports.filter(x=>!x.id.startsWith("legacy-"));localStorage.setItem(STORAGE_KEY,JSON.stringify(remaining));localStorage.setItem(FILES_KEY,JSON.stringify(next));setImports(next);setRows([]);setFile("");setMsg("All legacy uploads were cleared. Re-upload your TrackMan files and each new upload will be individually deletable.");return}if(!window.confirm(`Delete ${record.name} and its ${record.count.toLocaleString()} pitches from the season?`))return;const existing:Pitch[]=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");const remaining=existing.filter(p=>p.importId!==id);const next=imports.filter(x=>x.id!==id);localStorage.setItem(STORAGE_KEY,JSON.stringify(remaining));localStorage.setItem(FILES_KEY,JSON.stringify(next));setImports(next);setRows([]);setFile("");setMsg(`Deleted ${record.name} and removed ${record.count.toLocaleString()} pitches from the season.`)}
 useEffect(()=>{setImports(readImports())},[]);
 return <main><header><div><div className="eyebrow">RACERS BASEBALL</div><h1>TrackMan Import</h1><p>Upload a TrackMan CSV or Excel export. Each new file is added to your running season dataset in this browser.</p></div><a className="badge" href="/dashboard">← Coach Dashboard</a></header>
<section className="upload"><div className="uploadIcon"><Upload/></div><div><h2>Upload your TrackMan file</h2><p>CSV, XLSX, and XLS files are supported. TrackMan location, velocity, spin, exit velocity, launch angle and pitch type fields are normalized automatically.</p><label className="button"><FileSpreadsheet size={18}/>{busy?"Importing…":"Choose CSV / XLSX"}<input type="file" accept=".csv,.xlsx,.xls" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label>{file&&<span className="filename">{file}</span>}{msg&&<div className={msg.startsWith("Imported")?"success":"error"}>{msg.startsWith("Imported")?<CheckCircle2 size={17}/>:<AlertCircle size={17}/>} {msg}</div>}{rows.length>0&&<a className="button dashboardLink" href="/dashboard"><ArrowRight size={18}/> Open Season Dashboard</a>}</div></section>
<div className="grid four"><Card icon={<Database/>} label="This File" value={rows.length.toLocaleString()}/><Card icon={<Users/>} label="Hitters" value={hitters.length}/><Card icon={<Target/>} label="Pitchers" value={pitchers.length}/><Card icon={<Activity/>} label="Avg Velocity" value={velo?velo.toFixed(1)+" mph":"—"}/></div>
<div className="grid three"><Stat title="Average Exit Velocity" value={ev?ev.toFixed(1)+" mph":"—"}/><Stat title="Average Spin" value={spin?Math.round(spin).toLocaleString()+" rpm":"—"}/><Stat title="Season Storage" value="Running total"/></div><section className="panel importHistory"><div className="panelHead"><div><h2>Imported Files</h2><p>Delete individual imports from the running season dataset.</p></div><Database/></div><div className="importList">{imports.some(x=>x.id.startsWith("legacy-"))&&<button className="deleteBtn legacyErase" onClick={()=>deleteImport(imports.find(x=>x.id.startsWith("legacy-"))!.id)}>Erase All Legacy Imports</button>}{imports.map(x=><div className="importRow" key={x.id}><div><strong>{x.name}</strong><small>{x.count?x.count.toLocaleString()+" pitches":"Legacy import"}{x.importedAt?" · "+new Date(x.importedAt).toLocaleString():""}</small></div><button className="deleteBtn" disabled={x.id.startsWith("legacy-")} onClick={()=>deleteImport(x.id)}>{x.id.startsWith("legacy-")?"Legacy — clear above":"Erase Import"}</button></div>)}</div></section>
{rows.length>0&&<section className="panel"><h2>Imported preview</h2><div className="tableWrap"><table><thead><tr><th>Pitcher</th><th>Batter</th><th>Pitch</th><th>Velo</th><th>Exit Velo</th><th>Spin</th></tr></thead><tbody>{rows.slice(0,20).map(r=><tr key={r.id}><td>{r.pitcher}</td><td>{r.batter}</td><td>{r.pitchType}</td><td>{r.velo??"—"}</td><td>{r.exitVelo??"—"}</td><td>{r.spin??"—"}</td></tr>)}</tbody></table></div></section>}
<footer>Racers TrackMan Analytics · Import workspace</footer></main>}
function Card({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="card"><span>{icon}</span><small>{label}</small><strong>{value}</strong></div>}
function Stat({title,value}:{title:string;value:string}){return <div className="stat"><small>{title}</small><strong>{value}</strong></div>}