"use client";
import {useMemo,useState} from "react";
import {BarChart3,Users,Target,Upload,Filter,ChevronDown} from "lucide-react";

type Pitch={pitcher:string;batter:string;pitchType:string;pitchCall:string;velo:number|null;exitVelo:number|null;angle:number|null;spin:number|null;side:number|null;height:number|null;date:string};
const demo:Pitch[]=[
{pitcher:"Season data",batter:"Upload TrackMan",pitchType:"—",pitchCall:"—",velo:null,exitVelo:null,angle:null,spin:null,side:null,height:null,date:""}
];
function avg(a:(number|null)[]){const x=a.filter((v):v is number=>v!==null);return x.length?x.reduce((s,v)=>s+v,0)/x.length:0}
export default function Dashboard(){
 const [tab,setTab]=useState("Overview"); const [player,setPlayer]=useState("All Players"); const [type,setType]=useState("All Pitches");
 const data=demo; const avgV=avg(data.map(x=>x.velo)); const avgEV=avg(data.map(x=>x.exitVelo));
 return <main className="dash"><aside><div className="brand">RACERS<br/><span>TRACKMAN</span></div><nav>{["Overview","Hitters","Pitchers","Heat Maps","Imports"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><div className="sideFoot">Murray State Baseball<br/>Analytics workspace</div></aside><section className="content"><header><div><div className="eyebrow">COACH DASHBOARD</div><h1>{tab}</h1><p>Season-long TrackMan performance and pitch-level analysis.</p></div><a className="uploadBtn" href="/import"> <Upload size={17}/> Import Data</a></header><div className="filters"><label><Filter size={15}/> Player <select value={player} onChange={e=>setPlayer(e.target.value)}><option>All Players</option></select></label><label>Pitch Type <select value={type} onChange={e=>setType(e.target.value)}><option>All Pitches</option></select></label><label>Date Range <select><option>Entire Season</option><option>Last 5 Games</option><option>Last 10 Games</option></select></label></div><div className="metrics"><Metric title="Pitches" value="—"/><Metric title="Avg. Velocity" value={avgV?avgV.toFixed(1)+" mph":"—"}/><Metric title="Avg. Exit Velo" value={avgEV?avgEV.toFixed(1)+" mph":"—"}/><Metric title="Players" value="—"/></div><div className="two"><section className="panel"><div className="panelHead"><h2>Season Overview</h2><BarChart3 size={18}/></div><div className="empty"><Target size={30}/><strong>Import your first TrackMan file</strong><span>Your season charts will populate here automatically.</span><a href="/import">Go to importer</a></div></section><section className="panel"><div className="panelHead"><h2>Player Reports</h2><Users size={18}/></div><div className="empty"><Users size={30}/><strong>Individual reports</strong><span>Hitter and pitcher profiles will appear after import.</span></div></section></div><section className="panel"><div className="panelHead"><div><h2>Heat Map Workspace</h2><p>Choose a player, pitch type, count or date range to analyze location.</p></div><ChevronDown size={18}/></div><div className="heat"><div className="zone"><div className="strike"></div></div><div className="heatText"><strong>Strike-zone visualization</strong><span>Pitch location and batted-ball maps will be generated from imported TrackMan observations.</span></div></div></section></section></main>}
function Metric({title,value}:{title:string;value:string}){return <div className="metric"><small>{title}</small><strong>{value}</strong></div>}