"use client";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,Users,Target,Upload,Filter,Activity,Map,RefreshCw,Database,Printer} from "lucide-react";

type Pitch={id:number;pitcher:string;batter:string;pitchType:string;pitchCall:string;playResult:string;velo:number|null;exitVelo:number|null;angle:number|null;spin:number|null;spinAxis:number|null;side:number|null;height:number|null;date:string};
const STORAGE_KEY="racers-trackman-pitches-v1";

function avg(a:(number|null)[]){const x=a.filter((v):v is number=>v!==null);return x.length?x.reduce((s,v)=>s+v,0)/x.length:0}
function avgExit(a:(number|null)[]){return avg(a.map(v=>v!==null&&v>0?v:null))}
function max(a:(number|null)[]){const x=a.filter((v):v is number=>v!==null);return x.length?Math.max(...x):0}
function uniq(a:string[]){return Array.from(new Set(a.filter(Boolean))).sort()}
function isSwingingStrike(p:Pitch){const s=(p.pitchCall+" "+p.playResult).toLowerCase();return s.includes("swinging strike")||s.includes("swingingstrike")||s.includes("strikeout")||s.includes("whiff")}\nfunction isSwing(p:Pitch){const s=(p.pitchCall+" "+p.playResult).toLowerCase();return s.includes("swing")||s.includes("strikeout")||s.includes("foul")||s.includes("in play")||s.includes("inplay")||s.includes("hit")||s.includes("out")}
function isBip(p:Pitch){return p.exitVelo!==null}
function isHard(p:Pitch){return p.exitVelo!==null&&p.exitVelo>=95}

export default function Dashboard(){
 const [tab,setTab]=useState("Overview");const [data,setData]=useState<Pitch[]>([]);const [player,setPlayer]=useState("All Players");const [type,setType]=useState("All Pitches");const [date,setDate]=useState("All Dates");const [heatMode,setHeatMode]=useState<"pitches"|"batted">("pitches");const [heatPlayer,setHeatPlayer]=useState("Team");const [heatPitch,setHeatPitch]=useState("All Pitches");const [heatEvent,setHeatEvent]=useState("All Pitches");
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");setData(saved.map((p:Pitch)=>({...p,exitVelo:p.exitVelo!==null&&p.exitVelo>0?p.exitVelo:null})))}catch{setData([])}},[]);
 const pitchers=useMemo(()=>uniq(data.map(x=>x.pitcher).filter(x=>x!=="Unknown")),[data]);const hitters=useMemo(()=>uniq(data.map(x=>x.batter).filter(x=>x!=="Unknown")),[data]);const pitchTypes=useMemo(()=>uniq(data.map(x=>x.pitchType).filter(x=>x!=="Unknown")),[data]);const dates=useMemo(()=>uniq(data.map(x=>x.date).filter(Boolean)),[data]);
 const filtered=useMemo(()=>data.filter(x=>(player==="All Players"||x.batter===player||x.pitcher===player)&&(type==="All Pitches"||x.pitchType===type)&&(date==="All Dates"||x.date===date)),[data,player,type,date]);
 const playerRows=useMemo(()=>tab==="Hitters"?data.filter(x=>x.batter===heatPlayer):data.filter(x=>x.pitcher===heatPlayer),[data,tab,heatPlayer]);
 const overviewV=avg(filtered.map(x=>x.velo));const overviewEV=avgExit(filtered.map(x=>x.exitVelo));const hard=filtered.filter(isHard).length;const bip=filtered.filter(isBip).length;
 const reload=()=>{try{setData(JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]"))}catch{}};
 const nav=["Overview","Hitters","Pitchers","Heat Maps","Imports"];
 return <main className="dash"><aside><div className="brand">RACERS<br/><span>TRACKMAN</span></div><nav>{nav.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><div className="sideFoot">Murray State Baseball<br/>Analytics workspace</div></aside><section className="content">
 <header><div><div className="eyebrow">COACH DASHBOARD</div><h1>{tab}</h1><p>Season-long TrackMan performance and pitch-level analysis.</p></div><div className="headerActions"><button className="iconBtn" onClick={reload} title="Refresh imported data"><RefreshCw size={16}/></button><button className="printBtn" onClick={()=>window.print()} title="Print or save this report as PDF"><Printer size={17}/> Print Report</button><a className="uploadBtn" href="/import"><Upload size={17}/> Import Data</a></div></header>
 <div className="filters"><label><Filter size={15}/> Player <select value={player} onChange={e=>setPlayer(e.target.value)}><option>All Players</option>{uniq([...hitters,...pitchers]).map(x=><option key={x}>{x}</option>)}</select></label><label>Pitch Type <select value={type} onChange={e=>setType(e.target.value)}><option>All Pitches</option>{pitchTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Date <select value={date} onChange={e=>setDate(e.target.value)}><option>All Dates</option>{dates.map(x=><option key={x}>{x}</option>)}</select></label></div>
 {tab==="Overview"&&<Overview data={filtered} hitters={hitters} pitchers={pitchers} avgV={overviewV} avgEV={overviewEV} hard={hard} bip={bip} setTab={setTab}/>}
 {tab==="Hitters"&&<HitterReport data={data} hitters={hitters} selected={player==="All Players"||!hitters.includes(player)?hitters[0]||"":player}/>}
 {tab==="Pitchers"&&<PitcherReport data={data} pitchers={pitchers} selected={player==="All Players"||!pitchers.includes(player)?pitchers[0]||"":player}/>}
 {tab==="Heat Maps"&&<HeatMaps data={data} hitters={hitters} pitchers={pitchers} mode={heatMode} setMode={setHeatMode} player={heatPlayer} setPlayer={setHeatPlayer} pitchFilter={heatPitch} setPitchFilter={setHeatPitch} eventFilter={heatEvent} setEventFilter={setHeatEvent}/>}
 {tab==="Imports"&&<ImportSummary data={data}/>}
 </section></main>
}

function Overview({data,hitters,pitchers,avgV,avgEV,hard,bip,setTab}:{data:Pitch[];hitters:string[];pitchers:string[];avgV:number;avgEV:number;hard:number;bip:number;setTab:(v:string)=>void}){
 return <><div className="metrics"><Metric title="Pitches" value={data.length.toLocaleString()}/><Metric title="Avg. Velocity" value={avgV?avgV.toFixed(1)+" mph":"—"}/><Metric title="Avg. Exit Velo" value={avgEV?avgEV.toFixed(1)+" mph":"—"}/><Metric title="Players" value={(hitters.length+pitchers.length).toString()}/></div><div className="two"><section className="panel"><div className="panelHead"><h2>Season Overview</h2><BarChart3 size={18}/></div><div className="reportGrid"><Stat title="Batted Balls" value={bip.toLocaleString()}/><Stat title="Hard-Hit (95+)" value={hard.toLocaleString()}/><Stat title="Hard-Hit %" value={bip?(hard/bip*100).toFixed(1)+"%":"—"}/><Stat title="Games / Dates" value={uniq(data.map(x=>x.date)).length.toString()}/></div></section><section className="panel"><div className="panelHead"><h2>Player Reports</h2><Users size={18}/></div><div className="quickLinks"><button onClick={()=>setTab("Hitters")}>Use the Hitters tab for individual hitter reports.</button><button onClick={()=>setTab("Pitchers")}>Use the Pitchers tab for individual pitching reports.</button><button onClick={()=>setTab("Heat Maps")}>Use Heat Maps for player or team location maps.</button></div></section></div><section className="panel"><div className="panelHead"><div><h2>Current Dataset</h2><p>Filters above apply to the overview metrics.</p></div><Target size={18}/></div><div className="tableWrap"><table><thead><tr><th>Player</th><th>Role</th><th>Pitches</th><th>Avg Velo</th><th>Avg EV</th></tr></thead><tbody>{[...hitters.map(p=>({p,role:"Hitter"})),...pitchers.map(p=>({p,role:"Pitcher"}))].slice(0,20).map(x=>{const r=data.filter(d=>d.batter===x.p||d.pitcher===x.p);return <tr key={x.p}><td>{x.p}</td><td>{x.role}</td><td>{r.length}</td><td>{avg(r.map(d=>d.velo)).toFixed(1)}</td><td>{avgExit(r.map(d=>d.exitVelo))?avgExit(r.map(d=>d.exitVelo)).toFixed(1):"—"}</td></tr>})}</tbody></table></div></section></>
}

function HitterReport({data,hitters,selected}:{data:Pitch[];hitters:string[];selected:string}){
 const [name,setName]=useState(selected);const rows=data.filter(x=>x.batter===name);const bip=rows.filter(isBip);const swings=rows.filter(isSwing);const whiffs=rows.filter(isSwingingStrike);const hard=bip.filter(isHard);const ev=avgExit(bip.map(x=>x.exitVelo));const la=avg(bip.map(x=>x.angle));
 return <><section className="panel"><div className="reportHeader"><div><div className="eyebrow">HITTER REPORT</div><h2>{name||"No hitter data yet"}</h2></div><select value={name} onChange={e=>setName(e.target.value)}>{hitters.map(x=><option key={x}>{x}</option>)}</select></div><div className="reportCards"><Metric title="Pitches Seen" value={rows.length.toLocaleString()}/><Metric title="Batted Balls" value={bip.length.toString()}/><Metric title="Avg Exit Velo" value={ev?ev.toFixed(1)+" mph":"—"}/><Metric title="Hard-Hit %" value={bip.length?(hard.length/bip.length*100).toFixed(1)+"%":"—"}/><Metric title="Swings" value={swings.length.toString()}/><Metric title="Swing & Miss" value={whiffs.length.toString()}/><Metric title="Whiff %" value={swings.length?(whiffs.length/swings.length*100).toFixed(1)+"%":"—"}/></div><div className="reportGrid"><Stat title="Max Exit Velo" value={max(bip.map(x=>x.exitVelo))?max(bip.map(x=>x.exitVelo)).toFixed(1)+" mph":"—"}/><Stat title="Avg Launch Angle" value={la?la.toFixed(1)+"°":"—"}/><Stat title="Pitch Types Seen" value={uniq(rows.map(x=>x.pitchType)).length.toString()}/><Stat title="Games / Dates" value={uniq(rows.map(x=>x.date)).length.toString()}/></div></section><section className="panel"><div className="panelHead"><h2>Pitch-Type Performance</h2><Activity size={18}/></div><div className="tableWrap"><table><thead><tr><th>Pitch</th><th>Seen</th><th>Avg EV</th><th>Hard Hit %</th></tr></thead><tbody>{uniq(rows.map(x=>x.pitchType)).map(t=>{const r=rows.filter(x=>x.pitchType===t);const b=r.filter(isBip);return <tr key={t}><td>{t}</td><td>{r.length}</td><td>{avgExit(b.map(x=>x.exitVelo))?avgExit(b.map(x=>x.exitVelo)).toFixed(1):"—"}</td><td>{b.length?(b.filter(isHard).length/b.length*100).toFixed(1)+"%":"—"}</td></tr>})}</tbody></table></div></section></>
}

function PitcherReport({data,pitchers,selected}:{data:Pitch[];pitchers:string[];selected:string}){
 const [name,setName]=useState(selected);const rows=data.filter(x=>x.pitcher===name);const velo=avg(rows.map(x=>x.velo));const spin=avg(rows.map(x=>x.spin));const swings=rows.filter(isSwing).length;const whiffs=rows.filter(isSwingingStrike).length;
 return <><section className="panel"><div className="reportHeader"><div><div className="eyebrow">PITCHER REPORT</div><h2>{name||"No pitcher data yet"}</h2></div><select value={name} onChange={e=>setName(e.target.value)}>{pitchers.map(x=><option key={x}>{x}</option>)}</select></div><div className="reportCards"><Metric title="Pitches" value={rows.length.toLocaleString()}/><Metric title="Avg Velocity" value={velo?velo.toFixed(1)+" mph":"—"}/><Metric title="Max Velocity" value={max(rows.map(x=>x.velo))?max(rows.map(x=>x.velo)).toFixed(1)+" mph":"—"}/><Metric title="Avg Spin" value={spin?Math.round(spin).toLocaleString()+" rpm":"—"}/></div><div className="reportGrid"><Stat title="Swings" value={swings.toString()}/><Stat title="Whiff %" value={swings?(whiffs/swings*100).toFixed(1)+"%":"—"}/><Stat title="Pitch Types" value={uniq(rows.map(x=>x.pitchType)).length.toString()}/><Stat title="Games / Dates" value={uniq(rows.map(x=>x.date)).length.toString()}/></div></section><section className="panel"><div className="panelHead"><h2>Pitch Arsenal</h2><Target size={18}/></div><div className="tableWrap"><table><thead><tr><th>Pitch</th><th>Usage</th><th>Avg Velo</th><th>Avg Spin</th></tr></thead><tbody>{uniq(rows.map(x=>x.pitchType)).map(t=>{const r=rows.filter(x=>x.pitchType===t);return <tr key={t}><td>{t}</td><td>{r.length}</td><td>{avg(r.map(x=>x.velo))?avg(r.map(x=>x.velo)).toFixed(1):"—"}</td><td>{avg(r.map(x=>x.spin))?Math.round(avg(r.map(x=>x.spin))).toLocaleString():"—"}</td></tr>})}</tbody></table></div></section></>
}

function HeatMaps({data,hitters,pitchers,mode,setMode,player,setPlayer,pitchFilter,setPitchFilter,eventFilter,setEventFilter}:{data:Pitch[];hitters:string[];pitchers:string[];mode:"pitches"|"batted";setMode:(v:"pitches"|"batted")=>void;player:string;setPlayer:(v:string)=>void;pitchFilter:string;setPitchFilter:(v:string)=>void;eventFilter:string;setEventFilter:(v:string)=>void}){
 const rows=data.filter(x=>player==="Team"||(mode==="batted"?x.batter===player:x.pitcher===player)).filter(x=>pitchFilter==="Hard Hit (95+ mph)"?(x.exitVelo!==null&&x.exitVelo>=95):(pitchFilter==="All Pitches"||x.pitchType.toLowerCase().includes(pitchFilter.toLowerCase()))).filter(x=>eventFilter==="Swing & Miss"?isSwingingStrike(x):true).filter(x=>x.side!==null&&x.height!==null).filter(x=>mode==="batted"?x.exitVelo!==null:true);
 const cells=Array.from({length:81},(_,i)=>({i,count:0}));for(const r of rows){const col=Math.max(0,Math.min(8,Math.floor(((r.side??0)+1.5)/3*9)));const row=Math.max(0,Math.min(8,8-Math.floor(((r.height??2.5)-1)/4*9)));cells[row*9+col].count++}const peak=Math.max(1,...cells.map(c=>c.count));
 return <><section className="panel"><div className="reportHeader"><div><div className="eyebrow">LOCATION ANALYSIS</div><h2>{mode==="pitches"?"Pitch Location Heat Map":"Batted-Ball Heat Map"}</h2><p>{rows.length.toLocaleString()} observations with usable location data.</p></div><div className="heatControls"><button className={mode==="pitches"?"smallActive":""} onClick={()=>{setMode("pitches");setPlayer("Team")}}>Pitch Location</button><button className={mode==="batted"?"smallActive":""} onClick={()=>{setMode("batted");setPlayer("Team")}}>Batted Ball</button><select value={player} onChange={e=>setPlayer(e.target.value)}><option>Team</option>{(mode==="batted"?hitters:pitchers).map(x=><option key={x}>{x}</option>)}</select><select value={pitchFilter} onChange={e=>setPitchFilter(e.target.value)}><option>All Pitches</option><option>Fastball</option><option>Sinker</option><option>Slider</option><option>Curveball</option><option>Splitter</option><option>Changeup</option><option>Hard Hit (95+ mph)</option></select><select value={eventFilter} onChange={e=>setEventFilter(e.target.value)}><option>All Results</option><option>Swing & Miss</option></select></div></div><div className="heatMapWrap"><div className="heatGrid">{cells.map(c=><div key={c.i} className="heatCell" style={{opacity:c.count?0.28+0.72*c.count/peak:0.08,backgroundColor:c.count?`hsl(${Math.round(240-(240*c.count/peak))},90%,50%)`:undefined}} title={c.count+" observations"}>{c.count||""}</div>)}<div className="strikeZone"/><span className="zoneLabel top">High</span><span className="zoneLabel bottom">Low</span></div><div className="heatLegend"><strong>{mode==="pitches"?"Pitch locations":"Contact locations"}</strong><span>Each square represents a location bucket from the TrackMan PlateLocSide / PlateLocHeight fields.</span><span>Color scale: blue = low · yellow = middle · red = high</span><span>Peak bucket: {peak} observation{peak===1?"":"s"}</span></div></div></section><section className="panel"><div className="panelHead"><h2>Heat Map Notes</h2><Map size={18}/></div><p className="muted">Use the filters and player selector to move from team-level location patterns to an individual hitter or pitcher. Pitch-type and date filters above also apply to this workspace.</p></section></>
}

function ImportSummary({data}:{data:Pitch[]}){const dates=uniq(data.map(x=>x.date).filter(Boolean));return <><section className="panel"><div className="panelHead"><div><h2>Season Import History</h2><p>Data currently stored in this browser.</p></div><DatabaseIcon/></div><div className="reportCards"><Metric title="Total Pitches" value={data.length.toLocaleString()}/><Metric title="Dates" value={dates.length.toString()}/><Metric title="Hitters" value={uniq(data.map(x=>x.batter).filter(x=>x!=="Unknown")).length.toString()}/><Metric title="Pitchers" value={uniq(data.map(x=>x.pitcher).filter(x=>x!=="Unknown")).length.toString()}/></div></section><section className="panel"><div className="tableWrap"><table><thead><tr><th>Date</th><th>Pitches</th><th>Hitters</th><th>Pitchers</th></tr></thead><tbody>{dates.map(d=>{const r=data.filter(x=>x.date===d);return <tr key={d}><td>{d}</td><td>{r.length}</td><td>{uniq(r.map(x=>x.batter).filter(x=>x!=="Unknown")).length}</td><td>{uniq(r.map(x=>x.pitcher).filter(x=>x!=="Unknown")).length}</td></tr>})}</tbody></table></div></section></>}
function DatabaseIcon(){return <Database/>}
function Metric({title,value}:{title:string;value:string}){return <div className="metric"><small>{title}</small><strong>{value}</strong></div>}
function Stat({title,value}:{title:string;value:string}){return <div className="stat"><small>{title}</small><strong>{value}</strong></div>}